version: '3'

services:
  budget_backend:
    build: ./budget-backend
    command: npm run start:dev
    container_name: budget_backend
    volumes:
      - ./budget-backend:/src/api/
    ports:
      - "3000:3000"
