version: '3'

services:
  budget_backend:
    build: ./budget-backend
    command: npm run start:dev
    container_name: budget_backend
    volumes:
      - ./budget-backend:/src/api/
    ports:
      - 3000:3000

  budget_frontend:
    build: ./budget-frontend
    command: ng serve --host 0.0.0.0 --configuration=docker --poll 1000
    container_name: budget_frontend
    volumes:
      - ./budget-frontend:/src/app/
    ports:
      - 4200:4200
